services:
  context-server:
    build: .
    command: python mcp/servers/context_server.py
    environment:
    - PYTHONPATH=/app
    ports:
    - 8001:8001
    volumes:
    - ./logs:/app/logs
    - ./data:/app/data
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
    - 14268:14268
    - 16686:16686
  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    volumes:
    - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  redis:
    image: redis:7-alpine
    ports:
    - 6379:6379
version: '3.8'
