alerts:
  cost_threshold: 50.0
  error_rate_threshold: 0.1
  response_time_threshold: 5.0
logging:
  format: structured
  level: INFO
  log_file: logs/mcp-agents.log
  max_size: 10MB
  output: file
  rotate: true
metrics:
  collection_interval: 30
  enabled: true
  export_endpoint: http://localhost:9090
  export_format: prometheus
tracing:
  enabled: true
  jaeger_endpoint: http://localhost:14268/api/traces
  service_name: mcp-agent-system
